[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
healthcheckPath = "/api/_health/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[environments.production]
branch = "main"

[environments.staging]  
branch = "develop"

[services.uptable]
source = "repo"